# For more info: 
#   https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml
window:
  startup_mode: Fullscreen
font:
  normal:
    family: FiraCode Nerd Font Mono
  size: 16.0
debug:
  log_level: Debug
  print_events: false
scrolling:
  history: 100000
  multiplier: 3

