# For more info: 
#   https://raw.githubusercontent.com/alacritty/alacritty/master/alacritty.yml
window:
  startup_mode: Fullscreen
font:
  normal:
    family: Fira Code
  size: 13.0
debug:
  log_level: Debug
  print_events: false
scrolling:
  history: 0

