# Use custom format
format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$rust\
$package\
$terraform\
$cmd_duration\
$status\
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style)"

[git_commit]
only_detached = false

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
